---
# TODO can this be done idempotently?
- name: Remove previous deployments past retention
  shell: |
    ls -1dt {{ php_app_home }}/deployments/* | tail -n +{{ php_app_deployments_to_retain | int + 1 }} | xargs rm -rf
    set -o pipefail
  when: php_app_deployments_to_retain > 0
