---
- name: create secretes directory
  file: >-
    dest={{ php_app_deployment_dir }}/secrets
    owner={{ php_app_user }}
    group={{ php_app_user }}
    mode=0750
    state=directory

- name: create env secrets file
  template: >-
    src={{ php_app_env_secrets_template }}
    dest={{ php_app_deployment_dir }}/secrets/env
    owner={{ php_app_user }}
    group={{ php_app_user }}
    mode=0640
  when: php_app_env_secrets_template is defined

- name: install supervisor configuration
  template: >-
    src={{ php_app_supervisor_conf }}
    dest=/etc/supervisor/conf.d/{{ php_app_user }}
    owner=root
    group=root
    mode=0644
  when:
    - php_app_supervisor_conf is defined
    - ansible_distribution_release == "trusty"
  notify: reload supervisor

- name: install crontab for php app
  copy: >-
    src={{ php_app_crontab }}
    dest=/etc/cron.d/{{ php_app_user }}
    owner=root
    group=root
    mode=0644
  when: php_app_crontab is defined
