---
- name: Install OS dependencies
  apt: name={{ packages }} state=present
  vars:
    packages:
      - apt-transport-https  # Ensure https support for apt is installed
      - unzip  # required for composer

# TODO consider using https://github.com/geerlingguy/ansible-role-php-versions
- name: Add repository for PHP
  apt_repository:
    repo: ppa:ondrej/php
  register: ppa

- name: Update Apt
  apt: update_cache=yes
  when: ppa is changed

- import_role:
    name: geerlingguy.php
  tags:
    - php
    - provision

- import_role:
    name: geerlingguy.php-mysql
  tags:
    - php
    - php-mysql
    - provision

- import_role:
    name: geerlingguy.php-memcached
  tags:
    - php
    - php-memcached
    - provision

- name: Configure secure cookie sessions
  copy: >-
    src=php_fpm_session.ini
    dest=/etc/php/{{ php_major_minor_version }}/fpm/conf.d/90-session.ini
    mode=0644
    owner=root
    group=root
  notify: reload php-fpm

# This is mostly for dashboard
- name: Configure cli for long-running worker jobs
  template: >-
    src=php_cli_worker.ini.j2
    dest=/etc/php/{{ php_major_minor_version }}/cli/conf.d/90-worker.ini
    mode=0644
    owner=root
    group=root
  notify: reload php-fpm

- name: Configure php-fpm pool
  lineinfile:
    dest: "/etc/php/{{ php_major_minor_version }}/fpm/pool.d/www.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "^.?request_terminate_timeout.?=.+$"
      line: "request_terminate_timeout={{ php_fpm_request_terminate_timeout }}"
  notify: reload php-fpm
  when: php_fpm_request_terminate_timeout is defined

- name: Set default php-cli
  alternatives:
    name: php
    path: /usr/bin/php{{ php_major_minor_version }}
  notify: restart php-fpm
