---
- name: fetch the php app into src dir
  git: >-
    repo={{ php_app_git_repo }}
    dest={{ php_app_deployment_dir }}/src
    version={{ php_app_git_version }}
    depth=1
    umask=0022
  become: yes
  become_user: "{{ php_app_user }}"

- name: install php dependencies
  composer:
    command: install
    arguments: "--ansi --no-dev --no-interaction --optimize-autoloader --no-scripts"
    working_dir: "{{ pip }}/src"
  environment:
    COMPOSER_DISCARD_CHANGES: "true"
  become: yes
  become_user: "{{ php_app_user }}"
