---
- name: Converge
  hosts: all
  roles:
    - role: datagov-deploy-php
      vars:
        php_major_minor_version: "7.2"
        php_enable_php_fpm: true
        php_max_execution_time: 30
        php_webserver_daemon: nginx
