---
- name: Converge
  hosts: all
  roles:
    - role: datagov-deploy-php
      vars:
        php_app_user: myapp
        php_app_git_repo: https://github.com/GSA/project-open-data-dashboard.git
        php_app_git_version: '20190308132800'
        php_major_minor_version: "7.2"
        php_enable_php_fpm: true
        php_max_execution_time: 30
        php_webserver_daemon: nginx
