---
- name: Converge
  hosts: all
  roles:
    - role: datagov-deploy-php
      vars:
        php_default_version_debian: "7.0"
        php_enable_php_fpm: true
        php_max_execution_time: 30
        php_webserver_daemon: nginx
